### PR TITLE
User end - Patch imgonlydel not working

### LINKED ISSUE #164: Delete images when post is deleted
What that title says when posts are deleted the files of the image are not deleted.

### PR DESCRIPTION
**Pull request by Apogate**
Admin panel still needs a patch, but the more I work on it, the more I see it continually needs to be gutted.

Fixes #164.

### CODE REVIEW

File: _core/admin/delpost.php [hunk 1]
```diff
@@ -74,11 +74,8 @@ function targeted($resno, $pwd, $imgonly = 0, $automatic = 0, $children = 1, $di
             $auser   = $mysql->escape_string($_COOKIE['saguaro_auser']);
             $adfsize = ($row['fsize'] > 0) ? 1 : 0;
             $adname  = str_replace('</span> <span class="postertrip">!', '#', $row['name']);
-            if ($imgonly) {
-                $imgonly = 1;
-            } else {
-                $imgonly = 0;
-            }
+            $imgonly = ($imgonly =="on") ? 1 : 0;
```
Comment (RePod) [inline _core/admin/delpost.php:77]: The hell is this?

Just pass it as a boolean to begin with. `on` is arbitrary enough as is.
